services:
  ms-checkin:
    image: ms-checkin
    ports:
      - "3000:80"
    build:      
      context: .
      dockerfile: Dockerfile
    #environment:   
    #  ConnectionStrings:AeropuertoDbConnectionString: "Server=localhost,14333;Database=AeropuertoDb;User Id=sa;Password=Diplomado."
    depends_on:
      - mssql 
  #  #command: ["dotnet", "ef", "database update"]
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"  
    ports:
      - "14333:1433"
    environment:
      MSSQL_SA_PASSWORD: "Diplomado."
      ACCEPT_EULA: "Y"
    volumes:
      - 'mssql-server-data:/var/mssql/data'
  
volumes:
  mssql-server-data: