
networks:
  MyDockerTest:
    driver: bridge

services:
  ms-checkin:
    image: ms-checkin
    ports:
      - "3000:80"
    build:      
      context: .
      dockerfile: Dockerfile
    networks:
      - MyDockerTest
    environment:   
      DB_CONNECTION_STRING: "host=mymssql;port=14333;database=AeropuertoDb;username=sa;password=Diplomado."
    depends_on:
      - mssql 
  mymssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"  
    ports:
      - "14333:1433"
    hostname: mssql
    environment:
      MSSQL_SA_PASSWORD: "Diplomado."
      ACCEPT_EULA: "Y"
    volumes:
      - 'mssql-server-data:/var/mssql/data'
  
volumes:
  ms-checkin-data:
  mssql-server-data: