// <auto-generated />
using System;
using CheckIn.Infraestructure.EF.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CheckIn.Infraestructure.EF.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20220506210917_InitialStructure")]
    partial class InitialStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CheckIn.Infraestructure.EF.ReadModel.CheckInReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EsAltaPrioridad")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("esAltaPrioridad");

                    b.Property<DateTime>("HoraCheckIn")
                        .HasColumnType("datetime")
                        .HasColumnName("horaCheckIn");

                    b.Property<string>("NroCheckIn")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("nroCheckIn");

                    b.HasKey("Id");

                    b.ToTable("CheckIn");
                });

            modelBuilder.Entity("CheckIn.Infraestructure.EF.ReadModel.EquipajeReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CheckInId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("EsFragil")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("esFragil");

                    b.Property<decimal>("Peso")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("peso");

                    b.HasKey("Id");

                    b.HasIndex("CheckInId");

                    b.ToTable("Equipaje");
                });

            modelBuilder.Entity("CheckIn.Infraestructure.EF.ReadModel.EquipajeReadModel", b =>
                {
                    b.HasOne("CheckIn.Infraestructure.EF.ReadModel.CheckInReadModel", "CheckIn")
                        .WithMany("DetalleEquipaje")
                        .HasForeignKey("CheckInId");

                    b.Navigation("CheckIn");
                });

            modelBuilder.Entity("CheckIn.Infraestructure.EF.ReadModel.CheckInReadModel", b =>
                {
                    b.Navigation("DetalleEquipaje");
                });
#pragma warning restore 612, 618
        }
    }
}
