// <auto-generated />
using System;
using CheckIn.Infraestructure.EF.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CheckIn.Infraestructure.EF.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    partial class ReadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CheckIn.Infraestructure.EF.ReadModel.CheckIn.CheckInReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EsAltaPrioridad")
                        .HasColumnType("int")
                        .HasColumnName("esAltaPrioridad");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime")
                        .HasColumnName("hora");

                    b.Property<string>("LetraAsiento")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("letraAsiento");

                    b.Property<int>("NroAsiento")
                        .HasColumnType("int")
                        .HasColumnName("nroAsiento");

                    b.Property<string>("NroCheckIn")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("nroCheckIn");

                    b.Property<Guid?>("ReservaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VueloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.HasIndex("VueloId");

                    b.ToTable("CheckIn");
                });

            modelBuilder.Entity("CheckIn.Infraestructure.EF.ReadModel.CheckIn.EquipajeReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CheckInId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<int>("EsFragil")
                        .HasColumnType("int")
                        .HasColumnName("esFragil");

                    b.Property<decimal>("Peso")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("peso");

                    b.HasKey("Id");

                    b.HasIndex("CheckInId");

                    b.ToTable("Equipaje");
                });

            modelBuilder.Entity("CheckIn.Infraestructure.EF.ReadModel.Reserva.ReservaReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime")
                        .HasColumnName("hora");

                    b.Property<int>("NroReserva")
                        .HasColumnType("int")
                        .HasColumnName("nroReserva");

                    b.Property<Guid?>("VueloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VueloId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("CheckIn.Infraestructure.EF.ReadModel.Vuelo.VueloReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Destino")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("destino");

                    b.Property<int>("NroVuelo")
                        .HasColumnType("int")
                        .HasColumnName("nroVuelo");

                    b.Property<string>("Origen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("origen");

                    b.HasKey("Id");

                    b.ToTable("Vuelo");
                });

            modelBuilder.Entity("CheckIn.Infraestructure.EF.ReadModel.CheckIn.CheckInReadModel", b =>
                {
                    b.HasOne("CheckIn.Infraestructure.EF.ReadModel.Reserva.ReservaReadModel", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId");

                    b.HasOne("CheckIn.Infraestructure.EF.ReadModel.Vuelo.VueloReadModel", "Vuelo")
                        .WithMany()
                        .HasForeignKey("VueloId");

                    b.Navigation("Reserva");

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("CheckIn.Infraestructure.EF.ReadModel.CheckIn.EquipajeReadModel", b =>
                {
                    b.HasOne("CheckIn.Infraestructure.EF.ReadModel.CheckIn.CheckInReadModel", "CheckIn")
                        .WithMany("DetalleEquipaje")
                        .HasForeignKey("CheckInId");

                    b.Navigation("CheckIn");
                });

            modelBuilder.Entity("CheckIn.Infraestructure.EF.ReadModel.Reserva.ReservaReadModel", b =>
                {
                    b.HasOne("CheckIn.Infraestructure.EF.ReadModel.Vuelo.VueloReadModel", "Vuelo")
                        .WithMany()
                        .HasForeignKey("VueloId");

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("CheckIn.Infraestructure.EF.ReadModel.CheckIn.CheckInReadModel", b =>
                {
                    b.Navigation("DetalleEquipaje");
                });
#pragma warning restore 612, 618
        }
    }
}
